---
name: 'Release'

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME}}

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.release.outputs.version }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.27.0
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
          tag_prefix: "v"
          release_name: "<RELEASE_VERSION>"

      - name: Check Output Parameters
        id: release_parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "RELEASE_NUMBER=${{ steps.release.outputs.version }}" >> $GITHUB_OUTPUT


  build_and_push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: ${{ github.event.label.name != 'norelease' }}
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image for amd64 and amd64
        run: |
          docker buildx build --push \
            --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:"${{ needs.create-github-release.outputs.output1 }}" \
            --platform amd64,arm64 .
