---
name: 'Release'

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME}}

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.27.0
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
          tag_prefix: "v"
          release_name: "<RELEASE_VERSION>"

      - name: Check Output Parameters
        id: release_parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "${{ steps.release.outputs.version }}" >> $GITHUB_OUTPUT


  build_and_push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image for x86_64
        run: docker build . --file Dockerfile --platform x86_64
          --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{needs.create-github-release.outputs.output1}}

      - name: Build Docker Image for arm64
        run: docker build . --file Dockerfile --platform arm64
          --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{needs.create-github-release.outputs.output1}}

      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{needs.create-github-release.outputs.output1}}
