---
name: Spellcheck Action

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.28.0
      name: Spellcheck
      with:
        config_path: config/.spellcheck.yml
        source_files: README.md
        task_name: Markdown

